# -*- coding: utf-8 -*-
"""Movie Rating Analysis using Spark.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ww9bnP7lus8tSHPwwiZJKQDbSgyfxzmk

“We are installing PySpark library so that we can use Apache Spark in Google Colab.”
!pip install pyspark
– Create Spark Session
because SparkSession is entry point of Spark.

It starts Spark engine.

Without SparkSession, Spark cannot run.

Analogy:
SparkSession is like turning on the engine of a car
"""

#STEP 1 – Start Spark
from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("Movie Recommendation Project") \
    .getOrCreate()

"""#STEP 2 – Upload Dataset in Colab
Upload:

ratings.csv

movies.csv
# EXplanation

spark.read.csv → loads file

header=True → first row is column names

inferSchema=True → automatically detect data types

Explain:

DataFrame is like a table in SQL.
"""

#STEP 2 – Load Dataset
ratings = spark.read.csv("/content/rating.csv", header=True, inferSchema=True)
movies = spark.read.csv("/content/movie.csv", header=True, inferSchema=True)

ratings.show(5)
movies.show(5)

"""# Explain:

Why join?

Because:
ratings has rating
movies has title

We join to get:
userId | title | rating | genres

Analogy:

Joining two tables is like combining two sheets in Excel using common column.


"""

#STEP 3 – Join Both Tables
df = ratings.join(movies, on="movieId")

df.show(5)

"""









# Explain Line-by-Line:

groupBy("title") → group data by movie

---


avg("rating") → calculate average
count("rating") → total ratings
filter > 50 → remove movies with few ratings
orderBy → highest first

Important point:

A movie rated by only 1 user is not reliable."""

#STEP 4 –Top Rated Movies
from pyspark.sql.functions import avg, count

top_rated = df.groupBy("title") \
    .agg(avg("rating").alias("avg_rating"),
         count("rating").alias("total_ratings")) \
    .filter("total_ratings > 50") \
    .orderBy("avg_rating", ascending=False)

top_rated.show(10)

"""# Here we are not checking rating value.

We are checking:
Which movie has most number of ratings?

More ratings = More popularity
"""

#STEP 5 – Most Popular Movies

popular_movies = df.groupBy("title") \
    .agg(count("rating").alias("rating_count")) \
    .orderBy("rating_count", ascending=False)

popular_movies.show(10)

#STEP 6 – Most Active Users
active_users = df.groupBy("userId") \
    .agg(count("movieId").alias("movies_rated")) \
    .orderBy("movies_rated", ascending=False)

active_users.show(10)

#STEP 7 – Genre Wise Analysis
from pyspark.sql.functions import split, explode

genre_df = df.withColumn("genre", explode(split(df.genres, "\\|")))

genre_rating = genre_df.groupBy("genre") \
    .agg(avg("rating").alias("avg_rating")) \
    .orderBy("avg_rating", ascending=False)

genre_rating.show()

#STEP 8 – Basic Recommendation Logic
#Find users who liked a specific movie (rating >= 4)
liked_movie = df.filter((df.title == "Toy Story (1995)") & (df.rating >= 4))

liked_movie.show()

#Now find what else those users liked:
users = liked_movie.select("userId")

recommendations = df.join(users, "userId") \
    .groupBy("title") \
    .agg(avg("rating").alias("avg_rating")) \
    .orderBy("avg_rating", ascending=False)

recommendations.show(10)

"""🚀 ADVANCED VERSION WITH VISUALIZATIONS"""

top_rated_pd = top_rated.limit(10).toPandas()

import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.barh(top_rated_pd['title'], top_rated_pd['avg_rating'])
plt.xlabel("Average Rating")
plt.ylabel("Movie Title")
plt.title("Top Rated Movies")
plt.gca().invert_yaxis()
plt.show()

